# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

seeds = [{
  name: "Sunflower",
  plant_type: "Flowers",
  growing_season: "Summer",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Tomato",
  plant_type: "Vegetables",
  growing_season: "Spring",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Basil",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Apple Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Rose Bush",
  plant_type: "Shrubs",
  growing_season: "Spring",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Bluegrass",
  plant_type: "Grasses",
  growing_season: "Fall",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Tulip",
  plant_type: "Flowers",
  growing_season: "Spring",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Carrot",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Lavender",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Strawberry",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Azalea",
  plant_type: "Shrubs",
  growing_season: "Spring",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Bermuda Grass",
  plant_type: "Grasses",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Lily",
  plant_type: "Flowers",
  growing_season: "Summer",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Broccoli",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Mint",
  plant_type: "Herbs",
  growing_season: "Spring",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Cherry Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Daffodil",
  plant_type: "Flowers",
  growing_season: "Spring",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Cucumber",
  plant_type: "Vegetables",
  growing_season: "Summer",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Thyme",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Pear Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Lilac Bush",
  plant_type: "Shrubs",
  growing_season: "Spring",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Zoysia Grass",
  plant_type: "Grasses",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Roses",
  plant_type: "Flowers",
  growing_season: "Summer",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Spinach",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Parsley",
  plant_type: "Herbs",
  growing_season: "Spring",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Orange Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Lily of the Valley",
  plant_type: "Flowers",
  growing_season: "Spring",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Pepper",
  plant_type: "Vegetables",
  growing_season: "Summer",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Oregano",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Cherry Tomato",
  plant_type: "Vegetables",
  growing_season: "Summer",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Butterfly Bush",
  plant_type: "Shrubs",
  growing_season: "Spring",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Bermuda Grass",
  plant_type: "Grasses",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Tulip",
  plant_type: "Flowers",
  growing_season: "Spring",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Broccoli",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Mint",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Apple Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},{
  name: "Rosemary",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Pumpkin",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Lemon Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Hydrangea",
  plant_type: "Shrubs",
  growing_season: "Summer",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Shade-Tolerant",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Lavender",
  plant_type: "Flowers",
  growing_season: "Summer",
  seed_varieties: "Heirloom",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Kale",
  plant_type: "Vegetables",
  growing_season: "Fall",
  seed_varieties: "Organic",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
{
  name: "Bee Balm",
  plant_type: "Flowers",
  growing_season: "Summer",
  seed_varieties: "Native Species",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Direct Sowing",
  package_size: "Individual Packets",
},
{
  name: "Sage",
  plant_type: "Herbs",
  growing_season: "Summer",
  seed_varieties: "Non-GMO",
  planting_location: "Indoor",
  special_attributes: "Wildlife-Attracting",
  planting_method: "Transplanting",
  package_size: "Individual Packets",
},
{
  name: "Peach Tree",
  plant_type: "Fruits",
  growing_season: "Spring",
  seed_varieties: "Rare or Specialty",
  planting_location: "Outdoor",
  special_attributes: "Pollinator-Friendly",
  planting_method: "Transplanting",
  package_size: "Bulk or Wholesale",
},
{
  name: "Fescue Grass",
  plant_type: "Grasses",
  growing_season: "Fall",
  seed_varieties: "Non-GMO",
  planting_location: "Outdoor",
  special_attributes: "Drought-Tolerant",
  planting_method: "Direct Sowing",
  package_size: "Bulk or Wholesale",
},
]

seeds.each do |seed|
  Seed.create(seed)
end